name: dash_chat_2
description: The most complete Chat UI for flutter. Easy to use, highly customizable and fully featured
version: 0.0.22
homepage: https://github.com/SebastienBtr/Dash-Chat-2

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  audioplayers: ^5.0.0
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_parsed_text: ^2.2.1
  intl: ^0.19.0
  url_launcher: ^6.0.10
  video_player: ^2.2.5
  get: ^4.6.6
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  device_info_plus: ^9.1.2
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  chat_input: ^0.0.6

dependency_overrides:
  win32: 5.5.4
  image_picker: ^1.0.7

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
